version: "3"

services:
    client:
        image: nginx
        ports:
            - 8811:80
        volumes:
            - ./etc/nginx/html:/etc/nginx/html
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
